// AUTO GENERATED BY JNIGEN — DO NOT EDIT.
//
// Regenerate with: dart run jnigen --config jnigen.yaml
//
// Placeholder file. After running jnigen this will be replaced with actual
// JNI bindings for DeviceScreenBrightnessHelper.

// ignore_for_file: type=lint

import 'package:jni/jni.dart';

/// Dart wrapper for `com.example.device_screen_brightness.DeviceScreenBrightnessHelper`.
class DeviceScreenBrightnessHelper {
  final JObject _context;

  DeviceScreenBrightnessHelper(this._context) {
    _init();
  }

  late final JClass _helperClass;
  late final JObject _instance;

  void _init() {
    _helperClass = JClass.forName(
      r'com/example/device_screen_brightness/DeviceScreenBrightnessHelper',
    );
    final ctor = _helperClass.constructorId(r'(Landroid/content/Context;)V');
    _instance = ctor.call<JObject>(_helperClass, [_context]);
  }

  int getScreenBrightness() {
    final methodId = _helperClass.instanceMethodId(
      r'getScreenBrightness',
      r'()I',
    );
    return methodId.call<jint, int>(_instance, jint.type, []);
  }

  int setScreenBrightness(int value) {
    final methodId = _helperClass.instanceMethodId(
      r'setScreenBrightness',
      r'(I)I',
    );
    return methodId.call<jint, int>(_instance, jint.type, [JValueInt(value)]);
  }

  int getAppBrightness() {
    final methodId = _helperClass.instanceMethodId(r'getAppBrightness', r'()I');
    return methodId.call<jint, int>(_instance, jint.type, []);
  }

  int setAppBrightness(int value) {
    final methodId = _helperClass.instanceMethodId(
      r'setAppBrightness',
      r'(I)I',
    );
    return methodId.call<jint, int>(_instance, jint.type, [JValueInt(value)]);
  }

  bool canWrite() {
    final methodId = _helperClass.instanceMethodId(r'canWrite', r'()Z');
    return methodId.call<jboolean, bool>(_instance, jboolean.type, []);
  }

  void requestPermission() {
    final methodId = _helperClass.instanceMethodId(
      r'requestPermission',
      r'()V',
    );
    methodId.call<jvoid, void>(_instance, jvoid.type, []);
  }
}
